FROM ubuntu

# RUN apt-get update \
#   && apt-get install -y apt apt-utils dialog mc aptitude php7.4 php7.4-intl php7.4-xml php7.4-curl php7.4-mbstring php7.4-gd php7.4-zip unzip adminer git


COPY index.php /var/www/html/
COPY compone /var/www/html/
COPY composer /var/www/html/
COPY app_local.php /var/www/html/
COPY 000-default.conf /etc/apache2/sites-available/
COPY php.ini /etc/php/7.4/apache2/

# componer
#RUN /var/www/html/compone webtareas2
#RUN mv /var/www/html/app_local.php /var/www/html/webtareas2/config
#RUN cd /var/www/html/webtareas2; chown www-data:www-data -R *
#RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

WORKDIR /var/www/html
CMD ["apachectl", "-D", "FOREGROUND"]
EXPOSE 80


